spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 15236479
  jpa:
    hibernate:
      ddl-auto: update
#      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # org.hibernate.dialect.MySQL5InnoDBDialect